---
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 15
  rebase-strategy: disabled
