#########################
## Starter config file
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 1500
# File Options
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/fonts/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1
  mixins-before-declarations:
    - 1
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 0
  no-duplicate-properties: 2
  hex-notation:
    - 0
    -
      style: uppercase
  indentation:
    - 0
    -
      size: 1
  property-sort-order:
    - 0
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 1
    -
      properties:
        - margin
        - padding
        - height
        - color
        - background-color
        - font-size
        - letter-spacing
        - line-height
        - font-family
        - border-radius
        - border-color
        - border-width