import * as React from 'react';
import { select } from '@storybook/addon-knobs';
import Icon from './Icon';

export default {
  title: 'Components/Data Display/Icon',
};

const iconNames = {
  'add-event': 'add-event',
  'add-member': 'add-member',
  alert: 'alert',
  alerts: 'alerts',
  archive: 'archive',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  assignments: 'assignments',
  availability: 'availability',
  'caret-down': 'caret-down',
  cart: 'cart',
  check: 'check',
  'check-circle-fill': 'check-circle-fill',
  computer: 'computer',
  'credit-card': 'credit-card',
  dashboard: 'dashboard',
  directory: 'directory',
  dismiss: 'dismiss',
  divisions: 'divisions',
  doc: 'doc',
  down: 'down',
  download: 'download',
  drag: 'drag',
  edit: 'edit',
  export: 'export',
  fees: 'fees',
  file: 'file',
  forms: 'forms',
  grid: 'grid',
  home: 'home',
  import: 'import',
  inbox: 'inbox',
  info: 'info',
  installments: 'installments',
  left: 'left',
  loader: 'loader',
  location: 'location',
  lock: 'lock',
  mail: 'mail',
  media: 'media',
  megaphone: 'megaphone',
  messages: 'messages',
  money: 'money',
  'new-season': 'new-season',
  'non-player': 'non-player',
  notifications: 'notifications',
  'page-layout': 'page-layout',
  photos: 'photos',
  piggybank: 'piggybank',
  plus: 'plus',
  pointer: 'pointer',
  posts: 'posts',
  preview: 'preview',
  public: 'public',
  refresh: 'refresh',
  registration: 'registration',
  'remove-member': 'remove-member',
  right: 'right',
  roster: 'roster',
  rostering: 'rostering',
  safety: 'safety',
  scale: 'scale',
  schedule: 'schedule',
  search: 'search',
  seasons: 'seasons',
  send: 'send',
  sent: 'sent',
  settings: 'settings',
  sort: 'sort',
  star: 'star',
  statistics: 'statistics',
  stopwatch: 'stopwatch',  
  'task-alt': 'task-alt',
  team: 'team',
  tracking: 'tracking',
  trash: 'trash',
  up: 'up',
  video: 'video',
  waiver: 'waiver',
};

const iconSizes = {
  Default: '',
  'Extra Small': 'u-fontSizeXs',
  Small: 'u-fontSizeSm',
  Medium: 'u-fontSizeMd',
  Large: 'u-fontSizeLg',
  'X-Large': 'u-fontSizeXl',
  'XX-Large': 'u-fontSizeXxl',
};

const iconColors = {
  Default: '',
  'Text Color': 'u-colorInfo',
  Negative: 'u-colorNegative',
  Positive: 'u-colorPositive',
  Primary: 'u-colorPrimary',
};

export const Default = () => (
  <Icon
    name={select('Icon', iconNames, 'home')}
    mods={`${select('Size', iconSizes, '')} ${select('Color', iconColors, '')}`}
  />
);
